"""Protocol-v2-local privacy and attack primitives.

This namespace is deliberately isolated from the frozen protocol-v1 benchmark.
"""

from purposebench.v2.privacy import (
    AggregateRelease,
    BudgetPolicyMismatch,
    DifferentialPrivacyEngine,
    DPTrainingConfig,
    DPTrainingResult,
    DuplicateReleaseError,
    MinimumCohortError,
    OptionalPrivacyDependencyError,
    PrivacyBudgetExceeded,
    PrivacyLedger,
    PrivacyLedgerEntry,
    PrivacyLedgerKey,
    PrivacySpec,
    default_dp_training_configs,
    dp_count,
    dp_group_comparison,
    dp_histogram,
    dp_mean,
    dp_rate,
    run_dp_training_suite,
    train_tabular_classifier,
)
from purposebench.v2.privacy_attacks import (
    PRIVACY_ATTACK_LIMITATIONS,
    REQUIRED_CONDITIONS,
    AttackComparison,
    AttackMeasurement,
    ConditionAttackInputs,
    PrivacyAttackReport,
    aggregate_reconstruction_attack,
    attribute_inference_attack,
    classification_utility,
    differencing_attack,
    evaluate_privacy_attacks,
    membership_inference_attack,
    repeated_query_averaging_attack,
)

__all__ = [
    "PRIVACY_ATTACK_LIMITATIONS",
    "REQUIRED_CONDITIONS",
    "AggregateRelease",
    "AttackComparison",
    "AttackMeasurement",
    "BudgetPolicyMismatch",
    "ConditionAttackInputs",
    "DPTrainingConfig",
    "DPTrainingResult",
    "DifferentialPrivacyEngine",
    "DuplicateReleaseError",
    "MinimumCohortError",
    "OptionalPrivacyDependencyError",
    "PrivacyAttackReport",
    "PrivacyBudgetExceeded",
    "PrivacyLedger",
    "PrivacyLedgerEntry",
    "PrivacyLedgerKey",
    "PrivacySpec",
    "aggregate_reconstruction_attack",
    "attribute_inference_attack",
    "classification_utility",
    "default_dp_training_configs",
    "differencing_attack",
    "dp_count",
    "dp_group_comparison",
    "dp_histogram",
    "dp_mean",
    "dp_rate",
    "evaluate_privacy_attacks",
    "membership_inference_attack",
    "repeated_query_averaging_attack",
    "run_dp_training_suite",
    "train_tabular_classifier",
]
